/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 */

#include "Platform_Types.h"

#define RCC_BASE   0X40021000
#define GPIOA_BASE   0X40010800

#define RCC_APB2ENR   *((vuint32_t *) (RCC_BASE+0x18) )
#define GPIOA_CRH     *((vuint32_t *) (GPIOA_BASE+0x04) )
#define GPIOA_ODR     *((vuint32_t *) (GPIOA_BASE+0x0C) )

typedef union {
	vuint32_t All_Port;
	struct {
		vuint32_t reserved : 13;
		vuint32_t pin_13 : 1 ;
	}Pin;
}PA_ODR_t;
int main(void)
{

	RCC_APB2ENR |= (1<<2) ;
	GPIOA_CRH &= 0xFF0FFFFF ;
	GPIOA_CRH |= 0x00200000 ;

	volatile PA_ODR_t* PA_ODR = (volatile PA_ODR_t* )(GPIOA_BASE+0x0C);
int i=0;
	while(1)
	{
		PA_ODR->Pin.pin_13 =1;
		for( i=0;i<5000;i++);
		PA_ODR->Pin.pin_13 =0;
		for(i=0;i<5000;i++);
	}
}
